#!/bin/bash

#set -x
set -e
set -o pipefail
set -o nounset

error_handler() {
   echo "###
$0 ERROR:
BASH_COMMAND: '$BASH_COMMAND'
failed with exit code '$?'.
###" >&2
   exit 1
}

trap error_handler ERR

source wiki-config
source credentials

[[ -v TMPFOLDER ]] || TMPFOLDER="/tmp/wiki-shell-temp"
[[ -v USERDOMAIN ]] || USERDOMAIN=""
[[ -v cookie_jar ]] || cookie_jar="$TMPFOLDER/wiki-cookiejar"

mkdir -p "$TMPFOLDER"
chmod og-rw "$TMPFOLDER"
