#!/bin/bash

#set -x
set -e
set -o pipefail
set -o nounset

error_handler() {
   echo "###
$0: ERROR:
BASH_COMMAND: '$BASH_COMMAND'
failed with exit code '$?'.
###" >&2
   exit 1
}

trap error_handler ERR

exit_handler() {
   local exit_code=$?
   if [ "$exit_code" = "0" ]; then
      echo "$0: INFO: END: with exit code: '$exit_code'"
   else
      echo "$0: ERROR: END: with exit code: '$exit_code'"
   fi
   exit "$exit_code"
}

trap exit_handler EXIT

source wiki-config

if test -f credentials ; then
   source credentials
fi

[[ -v TMPFOLDER ]] || TMPFOLDER="/tmp/wiki-shell-temp"
[[ -v USERDOMAIN ]] || USERDOMAIN=""
[[ -v cookie_jar ]] || cookie_jar="$TMPFOLDER/wiki-cookiejar"
[[ -v WIKI_API ]] || WIKI_API="${WIKI_URL}/${WIKI_SCRIPT_FOLDER}/api.php"
[[ -v WIKI_INDEX ]] || WIKI_INDEX="${WIKI_URL}/${WIKI_SCRIPT_FOLDER}/index.php"

mkdir -p "$TMPFOLDER"
chmod og-rw "$TMPFOLDER"
