#!/bin/bash

set -e
source common

TITLE="$1"
CONTENTS="$2"

if [ -z "$CONTENTS" ]; then
  echo "$0: ERROR: Syntax: $0 <page_to_edit> <new_content_file>"
  exit 1
fi

if [ ! -r "$CONTENTS" ]; then
  echo "$0: ERROR: File '$CONTENTS' does not exist!"
  exit 2
fi

echo "$0: INFO: Editing '${WIKI_API}' '$TITLE'..."
#echo "$0: INFO: Fetching edit token..."

curl \
   --fail \
   --silent \
   --show-error \
   --location \
   --cookie "$cookie_jar" \
   --cookie-jar "$cookie_jar" \
   --keepalive-time 60 \
   --header "Accept-Language: en-GB" \
   --header "Connection: keep-alive" \
   --compressed \
   --output "${TMPFOLDER}/fetch-edit-token.json" \
   --request "GET" \
   "${WIKI_API}?action=query&meta=tokens&format=json"

EDITTOKEN=$(jq --raw-output '.query.tokens.csrftoken' "${TMPFOLDER}/fetch-edit-token.json")

if [ "${#EDITTOKEN}" = 42 ]; then
   #echo "INFO: Edit token is: $EDITTOKEN"
   true "$0: INFO: Edit token OK."
else
   echo "$0: ERROR: Edit token not set."
   exit 1
fi

#echo "$0: INFO: Editing '$TITLE'..."

curl \
   --fail \
   --silent \
   --show-error \
   --location \
   --cookie "$cookie_jar" \
   --cookie-jar "$cookie_jar" \
   --keepalive-time 60 \
   --header "Accept-Language: en-GB" \
   --header "Connection: keep-alive" \
   --header "Expect:" \
   --data-urlencode "title=$TITLE" \
   --data-urlencode "text@$CONTENTS" \
   --data-urlencode "token=$EDITTOKEN" \
   --output "${TMPFOLDER}/edit-result.json" \
   --request "POST" \
   "${WIKI_API}?action=edit&format=json&"

echo "$0: INFO: Edit success."
