#!/bin/bash

set -e
source common
source wiki-config

TITLE="$1"
filename_with_contents="$2"

[[ -v edit_message ]] || edit_message="mediawiki-shell-bot-default-edit-message"

if [ -z "$filename_with_contents" ]; then
  echo "$0: ERROR: Syntax: $0 <page_to_edit> <new_content_file>"
  exit 1
fi

if [ ! -r "$filename_with_contents" ]; then
  echo "$0: ERROR: File '$filename_with_contents' does not exist!"
  exit 2
fi

file_content="$(cat "$filename_with_contents")"

if [ "$file_content" = "" ]; then
  echo "$0: ERROR: File '$filename_with_contents' must not be empty!"
  exit 3
fi

echo "$0: INFO: Editing '${WIKI_API}' '$TITLE'..."
#echo "$0: INFO: Fetching edit token..."

curl \
   --fail \
   --silent \
   --show-error \
   --location \
   --retry-connrefused \
   --retry 3 \
   --retry-delay 5 \
   --cookie "$cookie_jar" \
   --cookie-jar "$cookie_jar" \
   --keepalive-time 60 \
   --header "Accept-Language: en-GB" \
   --header "Connection: keep-alive" \
   --compressed \
   --output "${TMPFOLDER}/fetch-edit-token.json" \
   --request "GET" \
   "${WIKI_API}?action=query&meta=tokens&format=json"

EDITTOKEN=$(jq --raw-output '.query.tokens.csrftoken' "${TMPFOLDER}/fetch-edit-token.json")

if [ "${#EDITTOKEN}" = 42 ]; then
   #echo "INFO: Edit token is: $EDITTOKEN"
   true "$0: INFO: Edit token OK."
else
   echo "$0: ERROR: Edit token not set."
   exit 1
fi

#echo "$0: INFO: Editing '$TITLE'..."

curl \
   --fail \
   --silent \
   --show-error \
   --location \
   --retry-connrefused \
   --retry 3 \
   --retry-delay 5 \
   --cookie "$cookie_jar" \
   --cookie-jar "$cookie_jar" \
   --keepalive-time 60 \
   --header "Accept-Language: en-GB" \
   --header "Connection: keep-alive" \
   --header "Expect:" \
   --data-urlencode "title=$TITLE" \
   --data-urlencode "text@$filename_with_contents" \
   --data-urlencode "token=$EDITTOKEN" \
   --output "${TMPFOLDER}/edit-result.json" \
   --request "POST" \
   "${WIKI_API}?action=edit&format=json&tags=mediawiki-shell&summary=${edit_message}&bot"

echo "$0: INFO: Network ok."

test -r "${TMPFOLDER}/edit-result.json"

edit_result_output="$(cat "${TMPFOLDER}/edit-result.json")"

edit_result_jq="$(echo "$edit_result_output" | jq -r ".edit.result")"

echo "$edit_result_output" | jq

if [ "$edit_result_jq" = "Success" ]; then
   echo "$0: INFO: Edit success."
   exit 0
fi

echo "$0: ERROR: Edit error." >&2

exit 1
