#!/bin/bash

# API documentation: http://www.mediawiki.org/wiki/API:Main_page

source wiki-config

TITLE="$1"
CONTENTS="$2"

if [ -z "$CONTENTS" ]; then
  echo "ERROR: Syntax: $0 <page_to_edit> <new_content_file>"
  exit 1
fi

if [ ! -r "$CONTENTS" ]; then
  echo "ERROR: File '$CONTENTS' does not exist!"
  exit 2
fi

echo "INFO: Fetching edit token..."

curl \
   --silent \
   --show-error \
   --location \
   --cookie "$cookie_jar" \
   --cookie-jar "$cookie_jar" \
   --keepalive-time 60 \
   --header "Accept-Language: en-GB" \
   --header "Connection: keep-alive" \
   --compressed \
   --output "${TMPFOLDER}/fetch-edit-token.json" \
   --request "GET" "${WIKIAPI}?action=query&meta=tokens&format=json"

EDITTOKEN=$(jq --raw-output '.query.tokens.csrftoken' "${TMPFOLDER}/fetch-edit-token.json")

if [ "${#EDITTOKEN}" = 42 ]; then
   #echo "INFO: Edit token is: $EDITTOKEN"
   echo "INFO: Edit token OK."
else
   echo "ERROR: Edit token not set."
   exit 1
fi

curl \
   --silent \
   --show-error \
   --location \
   --cookie "$cookie_jar" \
   --cookie-jar "$cookie_jar" \
   --keepalive-time 60 \
   --header "Accept-Language: en-GB" \
   --header "Connection: keep-alive" \
   --header "Expect:" \
   --data-urlencode "title=$TITLE" \
   --data-urlencode "text@$CONTENTS" \
   --data-urlencode "token=$EDITTOKEN" \
   --request "POST" "${WIKIAPI}?action=edit&format=json&"

echo "INFO: Edit success."
