#!/bin/bash

# API documentation: http://www.mediawiki.org/wiki/API:Main_page

source wiki-config

TITLE="$1"

if [ -z "${TITLE:-}" -o -n "${2:-}" ]; then
  echo "ERROR: Syntax: $0 <page_title>"
  exit 1
fi

## NOTE: Do not use 'echo' here as this script writes to stdout which is
##       processed by other scripts.
true "INFO: Fetching '${WIKIINDEX}' '$TITLE'..."

# curl \
# 	--fail \
#    --silent \
#    --show-error \
# 	--location \
# 	--cookie "$cookie_jar" \
# 	--cookie-jar "$cookie_jar" \
# 	--user-agent "Curl Shell Script" \
# 	--keepalive-time 60 \
# 	--header "Accept-Language: en-GB" \
# 	--header "Connection: keep-alive" \
# 	--header "Expect:" \
# 	--data-urlencode "title=$TITLE" \
# 	--request "POST" "${WIKIINDEX}?action=raw"

curl \
   --fail \
   --silent \
   --show-error \
	--location \
	--user-agent "Curl Shell Script" \
	--keepalive-time 60 \
	--header "Accept-Language: en-GB" \
	--header "Connection: keep-alive" \
	--header "Expect:" \
        "${WIKIINDEX}?title=$TITLE&action=raw"

true "INFO: Fetch success."
