#!/bin/bash

set -e
source common
source wiki-config

echo "$0: INFO: Logging out of $WIKI_API..."

curl \
   --fail \
   --silent \
   --show-error \
   --location \
   --retry 2 \
   --retry-delay 5\
   --cookie "$cookie_jar" \
   --cookie-jar "$cookie_jar" \
   --keepalive-time 60 \
   --header "Accept-Language: en-GB" \
   --header "Connection: keep-alive" \
   --compressed \
   --request "POST" \
   "${WIKI_API}?action=logout&format=txt"

echo "$0: INFO: OK, logged out."
