#!/bin/bash

set -e
source common

echo "INFO: Logging out of $WIKIAPI..."

curl \
   --fail \
   --silent \
   --show-error \
   --location \
   --retry 2 \
   --retry-delay 5\
   --cookie "$cookie_jar" \
   --cookie-jar "$cookie_jar" \
   --keepalive-time 60 \
   --header "Accept-Language: en-GB" \
   --header "Connection: keep-alive" \
   --compressed \
   --request "POST" \
   "${WIKIAPI}?action=logout&format=txt"

echo "INFO: OK, logged out."
