#!/bin/bash

## TODO:
## create a file:
## credentials
## with the following contents:
#[[ -v WIKI_API_USER_NAME ]] || WIKI_API_USER_NAME="username"
#[[ -v WIKI_API_USER_PASS ]] || WIKI_API_USER_PASS="password"
[[ -v WIKI_SCRIPT_FOLDER ]] || WIKI_SCRIPT_FOLDER="w"
