#!/bin/bash

#set -x
set -e

cd ..
source wiki-config

SOURCE_WIKI='https://www.kicksecure.com/w/index.php'

DESTINATION_WIKI=(
   'https://www.whonix.org/w/api.php?format=json'
)

COPY_WIKI_PAGES_LIST=(
   "Testpage14"
   "Testpage15"
)

./login

for copy_wiki_pages_item in ${COPY_WIKI_PAGES_LIST[@]} ; do
   echo "INFO: Fetching '$copy_wiki_pages_item'..."
   WIKIINDEX="$SOURCE_WIKI" ./fetch "$copy_wiki_pages_item" | tee "$TMPFOLDER/fetched-wiki-page" >/dev/null
   echo "INFO: Fetch success."

   wiki_page_content=$(cat "$TMPFOLDER/fetched-wiki-page")

   ./edit "$copy_wiki_pages_item" "$TMPFOLDER/fetched-wiki-page"
done
