#!/bin/bash
set -x
echo "$0: START"

set -e
cd ..

source common

## example:
#SOURCE_WIKI_URL='https://www.kicksecure.com'
#DESTINATION_WIKI_URL=(
#   'https://www.whonix.org'
#)

[[ -v SOURCE_WIKI_URL ]] || missing_variable SOURCE_WIKI_URL
[[ -v DESTINATION_WIKI_URL ]] || missing_variable DESTINATION_WIKI_URL
[[ -v copy_wiki_pages_item ]] || missing_variable copy_wiki_pages_item

WIKI_URL="$DESTINATION_WIKI_URL" \
   ./login

echo "$0: INFO: Fetching '$SOURCE_WIKI_URL' '$copy_wiki_pages_item'..."

rm -f "$TMPFOLDER/fetched-wiki-page"

WIKI_URL="$SOURCE_WIKI_URL" \
   ./fetch \
      "$copy_wiki_pages_item" | \
      tee "$TMPFOLDER/fetched-wiki-page" >/dev/null

test -f "$TMPFOLDER/fetched-wiki-page"

#cat "$TMPFOLDER/fetched-wiki-page"
#echo ""

echo "$0: INFO: Fetch success."

wiki_page_content=$(cat "$TMPFOLDER/fetched-wiki-page")

WIKI_URL="$DESTINATION_WIKI_URL" \
   ./edit "$copy_wiki_pages_item" "$TMPFOLDER/fetched-wiki-page"
