#!/bin/bash

echo "$0: START"

set -e
cd ..

source common

SOURCE_WIKI_URL='https://www.kicksecure.com'

DESTINATION_WIKI_URL=(
   'https://www.whonix.org'
)

#COPY_WIKI_PAGES_LIST=(
#   "Testpage14"
#   "Testpage15"
#)

COPY_WIKI_PAGES_LIST=(
   "Testpage14"
)

WIKI_URL="$DESTINATION_WIKI_URL" \
   ./login

for copy_wiki_pages_item in ${COPY_WIKI_PAGES_LIST[@]} ; do
   echo "$0: INFO: Fetching '$SOURCE_WIKI_URL' '$copy_wiki_pages_item'..."

   rm -f "$TMPFOLDER/fetched-wiki-page"

   WIKI_URL="$SOURCE_WIKI_URL" \
      ./fetch \
         "$copy_wiki_pages_item" | \
         tee "$TMPFOLDER/fetched-wiki-page" >/dev/null

   test -f "$TMPFOLDER/fetched-wiki-page"

   #cat "$TMPFOLDER/fetched-wiki-page"
   #echo ""

   echo "$0: INFO: Fetch success."

   wiki_page_content=$(cat "$TMPFOLDER/fetched-wiki-page")

   WIKI_URL="$DESTINATION_WIKI_URL" \
      ./edit "$copy_wiki_pages_item" "$TMPFOLDER/fetched-wiki-page"
done
