#!/bin/bash

echo "$0: START"

set -e
cd ..

[[ -v WIKI_API ]] || WIKI_URL="invalid.tld"
source common

# DESTINATION_WIKI=(
#    'https://www.kicksecure.com'
#    'https://www.whonix.org'
# )

[[ -v DESTINATION_WIKI ]] || DESTINATION_WIKI=(
   'https://www.whonix.org'
)

for DESTINATION_WIKI in ${DESTINATION_WIKI[@]} ; do
   WIKI_URL="$DESTINATION_WIKI"  \
      ./login
done
