#!/bin/bash

## TODO: unfinished

#set -x
set -e

cd ..
source wiki-config

## Not required for public wiki.
#./login

wiki_target="https://www.whonix.org/w/"

api_continue_or_not=""
parsed_all_pages=""

while true ; do
   all_pages=$(curl "$wiki_target/api.php?action=query&format=json&list=allpages&aplimit=500&apcontinue=$api_continue_or_not")

   #parsed_all_pages=$(echo "$all_pages" | jq -r ".query.allpages[] | {title: .title}| .title")
   parsed_all_pages+=$(echo "$all_pages" | jq -r ".query.allpages[] | .title | @sh")
   parsed_all_pages+="
"

   if ! api_continue_or_not=$(echo "$all_pages" | jq -r ".continue | .apcontinue") ; then
      break
   fi
   if [ "$api_continue_or_not" = "null" ]; then
      break
   fi
done

for item_from_all_pages in "$parsed_all_pages" ; do
    echo "item_from_all_pages: '$item_from_all_pages'"
done
