#!/bin/bash

#set -x
set -e
set -o pipefail
set -o nounset

missing_variable() {
   echo "$0: ERROR: $@"
   exit 1
}

error_handler() {
   last_exit_code="$?"
   [[ -v WIKI_INDEX ]] || WIKI_INDEX=""
   [[ -v TITLE ]] || TITLE=""
   [[ -v BASH_COMMAND ]] || BASH_COMMAND=""

   echo "###
$0: ERROR:

BASH_COMMAND: '$BASH_COMMAND'
failed with exit code '$last_exit_code'.

WIKI_INDEX: '$WIKI_INDEX'
TITLE: '$TITLE'

###" >&2
   exit 1
}

trap error_handler ERR

exit_handler() {
   local exit_code=$?
   if [ "$exit_code" = "0" ]; then
      echo "$0: INFO: END: with exit code: '$exit_code'"
   else
      echo "$0: ERROR: END: with exit code: '$exit_code'"
   fi
   exit "$exit_code"
}

set_curl_binary_default() {
   if commannd -v scurl &>/dev/null ; then
      curl=scurl
   else
      curl=curl
   fi
}

set_backup_page_item() {
   local backup_page_item search replace

   backup_page_item="$1"

   ## remove last letter ("'")
   backup_page_item="${backup_page_item::-1}"
   ## remove first letter ("'")
   backup_page_item="${backup_page_item:1}"

   search="'\''"
   replace="'"
   backup_page_item=$(echo "$backup_page_item" | str_replace "$search" "$replace")

   search="&"
   replace="%26"
   backup_page_item=$(echo "$backup_page_item" | str_replace "$search" "$replace")

   ## Same format as git-mediawiki: replace ' ' with '_'.
   ## Replace spaces with underscore.
   search=" "
   replace="_"
   backup_page_item=$(echo "$backup_page_item" | str_replace "$search" "$replace")

   echo "$backup_page_item"
}

set_backup_filename_item() {
   local backup_filename_item search replace

   backup_filename_item="$1"

   ## Same format as git-mediawiki: replace '/' with '%2F'.
   ## Also the file system does not accept files containing '/'.
   search="/"
   replace="%2F"
   backup_filename_item=$(echo "$backup_filename_item" | str_replace "$search" "$replace")

   ## Same format as git-mediawiki: add '.mw' file extension.
   backup_filename_item="${backup_filename_item}.mw"

   echo "$backup_filename_item"
}

trap exit_handler EXIT

[[ -v TMPFOLDER ]] || TMPFOLDER=~/mediawiki-shell/temp
[[ -v USERDOMAIN ]] || USERDOMAIN=""
[[ -v cookie_jar ]] || cookie_jar="$TMPFOLDER/wiki-cookiejar"
[[ -v curl ]] || set_curl_binary_default
[[ -v curl_opts ]] || curl_opts="\
   --fail \
   --silent \
   --show-error \
   --retry-connrefused \
   --retry 3 \
   --retry-delay 5 \
"

mkdir -p "$TMPFOLDER"
chmod og-rw "$TMPFOLDER"
